# bot info, don't change
host: 'irc.esper.net'
port: 6667
nick: 'Oracle'
ident: 'Oracle'
pass: 'wombat1'
realname: 'Toofifty'
channel: '#rapidtest'

# admin
server-bots:
    - 'RapidCreative'
    - 'RapidSurvival'
chat-log: false 
console-format: '%(asctime)s %(message)s'
receive-format: '>> [%d/%m %H:%M:%S]'
send-format: '<< [%d/%m %H:%M:%S]'
action-format: '!! [%d/%m %H:%M:%S]'

# spam handler
enabled: true
interval: 3
warn: 3
kick: 5
ban: 2
    
# oracle protection
auto-op: false
auto-kick: false
auto-add: false

# messages and gags
command-chars: 
    - '?'
    - '!'
    - 'Oracle, '
check-mail: true
welcome-message: true
join-message: true
use-colours: true

translate: false
say-responses: true
youtube-links: true

rick-roll: false

# developer
mode: 'not debug'
sudo-char: '?^'