# bot info, don't change
host: 'irc.esper.net'
port: 6667
nick: 'Oracle'
ident: 'Oracle'
pass: 'wombat1'
realname: 'Toofifty'
channel: '#rapid'

# admin
# chat-log is buggy, best not to use
server-bots:
    - 'RapidCreative'
    - 'RapidSurvival'
chat-log: false 
console-format: '%(asctime)s %(message)s'
receive-format: '>> [%d/%m %H:%M:%S]'
send-format: '<< [%d/%m %H:%M:%S]'
action-format: '!! [%d/%m %H:%M:%S]'

# auto actions
reload-interval: 7200
restart-interval: 86400

# spam handler
spam-handler: true
interval: 10
warn: 3
kick: 5
# unused
ban: 2
    
# on user join
# configurable (user) join message coming soon
use-json-whitelist: true
whitelist-location: 'http://h.jakelane.me:9001/api/v1/ircwhitelist'
auto-op: false
auto-kick: false
auto-add: false
join-message: true
check-mail: true

# messages and gags
command-chars: 
    - '?'
    - '!'
    - 'Oracle, '
welcome-message: "&11Oracle bot has joined the session. Use &13?help &11for guidance."

# translate somehow seems to always piss people
# off, though I'm not sure as to why :)
translate: false
say-responses: true
youtube-links: true
cleverbot: false

rick-roll: false

# games
trivia: true
trivia-interval: 1200
trivia-points: 100

rps-points: 50

# or set to false
random-points: false
random-min-interval: 600
random-max-interval: 3600

# developer
mode: 'not debug'
sudo-char: '?^'
command-line: true